name: learn-github-actions
on: [push]
jobs:
  docker-test:
      name: CI
      runs-on: ubuntu-latest
      env:
          DOCKER_BUILDKIT: "1"
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Build docker
          run: make build
        - name: Test docker
          run: make run